# Generated by Django 3.0.2 on 2026-04-09 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
